<?php

/**
 * BaseBlog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $body
 * @property Doctrine_Collection $Products
 * 
 * @method string              getTitle()    Returns the current record's "title" value
 * @method clob                getBody()     Returns the current record's "body" value
 * @method Doctrine_Collection getProducts() Returns the current record's "Products" collection
 * @method Blog                setTitle()    Sets the current record's "title" value
 * @method Blog                setBody()     Sets the current record's "body" value
 * @method Blog                setProducts() Sets the current record's "Products" collection
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product as Products', array(
             'refClass' => 'BlogProduct',
             'local' => 'blog_id',
             'foreign' => 'product_id'));

        $sfinlineobjectcontainertemplate0 = new sfInlineObjectContainerTemplate(array(
             'relations' => 
             array(
              0 => 'Products',
             ),
             ));
        $this->actAs($sfinlineobjectcontainertemplate0);
    }
}