<?php

/**
 * BaseBlogProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $blog_id
 * @property integer $product_id
 * 
 * @method integer     getBlogId()     Returns the current record's "blog_id" value
 * @method integer     getProductId()  Returns the current record's "product_id" value
 * @method BlogProduct setBlogId()     Sets the current record's "blog_id" value
 * @method BlogProduct setProductId()  Sets the current record's "product_id" value
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlogProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_product');
        $this->hasColumn('blog_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}