<?php

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property double $price
 * @property Doctrine_Collection $Blog
 * 
 * @method string              getTitle() Returns the current record's "title" value
 * @method double              getPrice() Returns the current record's "price" value
 * @method Doctrine_Collection getBlog()  Returns the current record's "Blog" collection
 * @method Product             setTitle() Sets the current record's "title" value
 * @method Product             setPrice() Sets the current record's "price" value
 * @method Product             setBlog()  Sets the current record's "Blog" collection
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('price', 'double', null, array(
             'type' => 'double',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Blog', array(
             'refClass' => 'BlogProduct',
             'local' => 'product_id',
             'foreign' => 'blog_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($sluggable0);
    }
}